---
context: mergify
git_email: noreply@mergify.io
workers: 5
base_url: "<required>"
subscription_url: "<required>"
integration_id: "<required>"
private_key: "<required>"
oauth_client_id: "<required>"
oauth_client_secret: "<required>"
webhook_secret: "<required>"

log_ratelimit: false
debug: false
flush_redis_on_startup: false
