name: Continuous Integration, fixtures re-recording

on:
  workflow_dispatch:

jobs:
  record:
    timeout-minutes: 10
    runs-on: ubuntu-20.04
    services:
      redis:
        image: redis:latest
        ports:
          - 6363:6379
    steps:
      - name: Checkout ðŸ›Žï¸
        uses: actions/checkout@v2.3.4

      - name: Setup Python ðŸ”§
        uses: actions/setup-python@v2.2.2
        with:
          python-version: 3.9.6

      - name: Build ðŸ”§ & Test ðŸ”
        run: |
          cat ${{ secrets.ENGINE_RECORD_TEST_ENV }} > test.env
          sudo apt install -y redis-server
          pip install tox
          tox -e record
