name: Trigger production pipeline workflow
on:
  push:
    branches:
      - main

jobs:
  trigger-syncer-workflow:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v4.0.2
        with:
          github-token: ${{ secrets.DEPLOY_BOT_PAT_TOKEN_FOR_SYNCER }}
          script: |
            var resp = await github.actions.createWorkflowDispatch({
              owner: "Mergifyio",
              repo: "mergify-engine-prod",
              workflow_id: ".github/workflows/syncer.yml",
              ref: "main",
            });
            console.log(resp)
